import { addDays, mondayOf } from '../calendar/dates';
import { frenchHolidaysRange } from '../calendar/frenchHolidays';
import { FORMAT_VERSION } from './types';
import type { IsoDate, TeamFile } from './types';

/**
 * Fichier d'équipe de démonstration, ancré sur la semaine de `today`
 * pour que la démo soit toujours « vivante » à l'ouverture.
 */
export function createDemoTeamFile(today: IsoDate): TeamFile {
  const w0 = mondayOf(today);
  /** Jour `dayOffset` (0 = lundi) de la semaine `weeks` relative à la semaine courante. */
  const d = (weeks: number, dayOffset = 0): IsoDate => addDays(w0, weeks * 7 + dayOffset);
  const year = Number(today.slice(0, 4));

  return {
    formatVersion: FORMAT_VERSION,
    app: 'CrewGantt',
    team: {
      name: 'Équipe Web (démo)',
      calendar: {
        workingDays: [1, 2, 3, 4, 5],
        holidays: frenchHolidaysRange(year, year + 1),
      },
    },
    projects: [
      { id: 'p-portail', name: 'Portail client', color: '#4f8ef7', archived: false, notes: '' },
      { id: 'p-interne', name: 'Outils internes', color: '#7bc47f', archived: false, notes: '' },
    ],
    resources: [
      {
        id: 'r-alice',
        name: 'Alice',
        kind: 'person',
        workingDays: [1, 2, 4, 5],
        exceptions: [{ from: d(3, 0), to: d(3, 4), percent: 0, reason: 'Congés' }],
        projectShares: [
          { projectId: 'p-portail', from: d(-4, 0), percent: 60 },
          { projectId: 'p-interne', from: d(-4, 0), percent: 40 },
        ],
      },
      {
        id: 'r-bob',
        name: 'Bob',
        kind: 'person',
        exceptions: [],
        projectShares: [
          { projectId: 'p-portail', from: d(-4, 0), percent: 100 },
          { projectId: 'p-interne', from: d(-4, 0), percent: 0 },
        ],
      },
      {
        id: 'r-chloe',
        name: 'Chloé',
        kind: 'person',
        exceptions: [],
        projectShares: [
          { projectId: 'p-portail', from: d(-4, 0), percent: 30 },
          { projectId: 'p-interne', from: d(-4, 0), percent: 70 },
        ],
      },
    ],
    tasks: [
      {
        id: 'g-conception',
        projectId: 'p-portail',
        parentId: null,
        order: 0,
        name: 'Conception',
        description: '',
        type: 'group',
        scheduling: 'effort',
        estimate: null,
        effort: 0,
        remaining: 0,
      progress: 0,
        status: 'in_progress',
        requirements: '',
        links: [],
        deadline: null,
        date: null,
        blocks: [],
        notes: [],
      },
      {
        id: 't-spec',
        projectId: 'p-portail',
        parentId: 'g-conception',
        order: 0,
        name: 'Spécifications',
        description: 'Cadrage fonctionnel du portail.',
        type: 'task',
        scheduling: 'effort',
        estimate: 5,
        effort: 5,
        remaining: 0,
      progress: 0,
        status: 'done',
        requirements: '',
        links: [],
        deadline: null,
        date: null,
        blocks: [
          {
            id: 'b-spec-1',
            from: d(-3, 0),
            to: d(-3, 4),
            assignments: [{ resourceId: 'r-bob', units: 100 }],
          },
        ],
        notes: [],
      },
      {
        id: 't-maq',
        projectId: 'p-portail',
        parentId: 'g-conception',
        order: 1,
        name: 'Maquettes',
        description: '',
        type: 'task',
        scheduling: 'effort',
        estimate: 8,
        effort: 10,
        remaining: 7,
      progress: 0,
        status: 'in_progress',
        requirements: 'UX confirmé · maquettes à valider client avant dev',
        links: [{ on: 't-spec', type: 'after-end', lag: 0 }],
        deadline: null,
        date: null,
        blocks: [
          {
            id: 'b-maq-1',
            from: d(-2, 0),
            to: d(-2, 1),
            assignments: [{ resourceId: 'r-bob', units: 100 }],
          },
          {
            id: 'b-maq-2',
            from: d(0, 0),
            to: null,
            assignments: [{ resourceId: 'r-alice', units: 80 }],
          },
        ],
        notes: [{ date: d(-1, 0), text: 'Reprise par Alice après le salon.' }],
      },
      {
        id: 'm-maq',
        projectId: 'p-portail',
        parentId: 'g-conception',
        order: 2,
        name: 'Maquettes validées',
        description: '',
        type: 'milestone',
        scheduling: 'effort',
        estimate: null,
        effort: 0,
        remaining: 0,
      progress: 0,
        status: 'todo',
        requirements: '',
        links: [{ on: 't-maq', type: 'after-end', lag: 0 }],
        deadline: null,
        date: d(2, 4),
        blocks: [],
        notes: [],
      },
      {
        id: 'g-dev',
        projectId: 'p-portail',
        parentId: null,
        order: 1,
        name: 'Développement',
        description: '',
        type: 'group',
        scheduling: 'effort',
        estimate: null,
        effort: 0,
        remaining: 0,
      progress: 0,
        status: 'todo',
        requirements: '',
        links: [],
        deadline: null,
        date: null,
        blocks: [],
        notes: [],
      },
      {
        id: 't-front',
        projectId: 'p-portail',
        parentId: 'g-dev',
        order: 0,
        name: 'Dév. front',
        description: '',
        type: 'task',
        scheduling: 'effort',
        estimate: 12,
        effort: 15,
        remaining: 15,
      progress: 0,
        status: 'todo',
        requirements: 'Maquettes en partie validées',
        links: [{ on: 't-maq', type: 'after-progress', progressDays: 2, lag: 0 }],
        deadline: null,
        date: null,
        blocks: [
          {
            id: 'b-front-1',
            from: d(1, 0),
            to: null,
            assignments: [{ resourceId: 'r-bob', units: 100 }],
          },
        ],
        notes: [],
      },
      {
        id: 't-back',
        projectId: 'p-portail',
        parentId: 'g-dev',
        order: 1,
        name: 'Dév. back',
        description: '',
        type: 'task',
        scheduling: 'effort',
        estimate: 12,
        effort: 12,
        remaining: 12,
      progress: 0,
        status: 'todo',
        requirements: '',
        links: [],
        deadline: null,
        date: null,
        blocks: [
          {
            id: 'b-back-1',
            from: d(0, 0),
            to: null,
            assignments: [{ resourceId: 'r-chloe', units: 100 }],
          },
        ],
        notes: [],
      },
      {
        id: 't-api',
        projectId: 'p-portail',
        parentId: 'g-dev',
        order: 2,
        name: 'Intégration API partenaires',
        description: '',
        type: 'task',
        scheduling: 'effort',
        estimate: 4,
        effort: 4,
        remaining: 4,
      progress: 0,
        status: 'todo',
        requirements: 'Accès sandbox partenaire (en attente client)',
        links: [{ on: 't-back', type: 'after-end', lag: 0 }],
        deadline: null,
        date: null,
        blocks: [{ id: 'b-api-1', from: d(5, 0), to: null, assignments: [] }],
        notes: [],
      },
      {
        id: 't-recette',
        projectId: 'p-portail',
        parentId: null,
        order: 2,
        name: 'Recette',
        description: '',
        type: 'task',
        scheduling: 'effort',
        estimate: 5,
        effort: 5,
        remaining: 5,
      progress: 0,
        status: 'todo',
        requirements: 'Serveur de recette dispo',
        links: [
          { on: 't-front', type: 'after-end', lag: 0 },
          { on: 't-back', type: 'after-end', lag: 0 },
        ],
        deadline: d(7, 4),
        date: null,
        blocks: [
          {
            id: 'b-recette-1',
            from: d(6, 0),
            to: null,
            assignments: [{ resourceId: 'r-alice', units: 100 }],
          },
        ],
        notes: [],
      },
      {
        id: 'm-v1',
        projectId: 'p-portail',
        parentId: null,
        order: 3,
        name: 'Livraison V1',
        description: '',
        type: 'milestone',
        scheduling: 'effort',
        estimate: null,
        effort: 0,
        remaining: 0,
      progress: 0,
        status: 'todo',
        requirements: '',
        links: [{ on: 't-recette', type: 'after-end', lag: 0 }],
        deadline: null,
        date: d(8, 4),
        blocks: [],
        notes: [],
      },
      {
        id: 'g-outils',
        projectId: 'p-interne',
        parentId: null,
        order: 4,
        name: 'Outillage interne',
        description: '',
        type: 'group',
        scheduling: 'effort',
        estimate: null,
        effort: 0,
        remaining: 0,
      progress: 0,
        status: 'in_progress',
        requirements: '',
        links: [],
        deadline: null,
        date: null,
        blocks: [],
        notes: [],
      },
      {
        id: 't-report',
        projectId: 'p-interne',
        parentId: 'g-outils',
        order: 0,
        name: 'Script de reporting',
        description: '',
        type: 'task',
        scheduling: 'effort',
        estimate: 5,
        effort: 6,
        remaining: 4,
      progress: 0,
        status: 'in_progress',
        requirements: '',
        links: [],
        deadline: null,
        date: null,
        blocks: [
          {
            id: 'b-report-1',
            from: d(-1, 0),
            to: null,
            assignments: [{ resourceId: 'r-chloe', units: 100 }],
          },
        ],
        notes: [],
      },
      {
        id: 't-ci',
        projectId: 'p-interne',
        parentId: 'g-outils',
        order: 1,
        name: 'Migration CI',
        description: '',
        type: 'task',
        scheduling: 'effort',
        estimate: 8,
        effort: 8,
        remaining: 8,
      progress: 0,
        status: 'todo',
        requirements: 'Accès admin à la forge',
        links: [{ on: 't-report', type: 'with-start', lag: 0 }],
        deadline: null,
        date: null,
        blocks: [
          {
            id: 'b-ci-1',
            from: d(2, 0),
            to: null,
            assignments: [{ resourceId: 'r-alice', units: 100 }],
          },
        ],
        notes: [],
      },
      {
        id: 't-doc',
        projectId: 'p-interne',
        parentId: 'g-outils',
        order: 2,
        name: 'Documentation interne',
        description: '',
        type: 'task',
        scheduling: 'effort',
        estimate: 3,
        effort: 3,
        remaining: 3,
      progress: 0,
        status: 'todo',
        requirements: '',
        links: [],
        deadline: null,
        date: null,
        blocks: [
          {
            id: 'b-doc-1',
            from: d(4, 0),
            to: null,
            assignments: [{ resourceId: 'r-chloe', units: 50 }],
          },
        ],
        notes: [],
      },
      {
        id: 't-proto-mobile',
        projectId: 'p-interne',
        parentId: 'g-outils',
        order: 3,
        name: 'Prototype mobile (abandonné)',
        description: '',
        type: 'task',
        scheduling: 'effort',
        estimate: 15,
        effort: 15,
        remaining: 10,
      progress: 0,
        status: 'cancelled',
        requirements: '',
        links: [],
        deadline: null,
        date: null,
        blocks: [
          {
            id: 'b-proto-1',
            from: d(-10, 0),
            to: d(-3, 0),
            assignments: [{ resourceId: 'r-alice', units: 100 }],
          },
        ],
        notes: [],
      },
      {
        id: 'm-ci',
        projectId: 'p-interne',
        parentId: 'g-outils',
        order: 4,
        name: 'CI migrée',
        description: '',
        type: 'milestone',
        scheduling: 'effort',
        estimate: null,
        effort: 0,
        remaining: 0,
      progress: 0,
        status: 'todo',
        requirements: '',
        links: [{ on: 't-ci', type: 'after-end', lag: 0 }],
        deadline: null,
        date: d(6, 2),
        blocks: [],
        notes: [],
      },
    ],
    baselines: [
      {
        id: 'bl-initial',
        name: 'Plan initial',
        createdAt: d(-3, 0),
        active: true,
        tasks: {
          't-maq': { blocks: [{ from: d(-2, 0), to: d(-1, 4) }], effort: 10 },
          't-front': { blocks: [{ from: d(0, 0), to: d(2, 4) }], effort: 15 },
        },
        milestones: { 'm-maq': d(1, 4), 'm-v1': d(7, 4) },
      },
    ],
    journal: [
      {
        date: d(-1, 0),
        type: 'meeting',
        summary: [
          'Maquettes : reste 7 j-h (était 8)',
          'Maquettes : Bob → Alice (80 %) à partir de cette semaine',
          'Alice : congés posés dans 3 semaines',
        ],
        note: 'Salon pro la semaine dernière, équipe réduite.',
        remainingTotal: 58,
      },
    ],
    ui: { zoom: 'week', projectFilter: null, collapsed: [], ignoredConflicts: [] },
  };
}
